### ISSUE TITLE
All http://www.ebi.ac.uk/swo/ URIs are broken

### ISSUE THREAD

**Issue by pitviper6** [data2health/menRva#90]
The Software Ontology seems to have been removed, along with the URIs that were created at that site. None of them resolve.

**Comment by fenekku** [comment]
@pitviper6 I think you got the wrong repository :smile: . This repository is not related in any way to the url you have posted, nor is Software Ontology something this repository deals with.

I will close this at the end of the day.

**Comment by pitviper6** [comment]
Oops, sorry about that!

Juliane
